### ISSUE TITLE
[BUG] OpenSSL is not available

### ISSUE THREAD

**Issue by eknori** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#62]
**HCL Product Version**
Notes V11.0.1FP3, V12 Domino V12 GA
Using branch feature/webapp_updates

**Describe the bug**
Docker container does not start after successful buld. 

**Error Message**
```
[root@docker domino-online-meeting-integration]# docker run -it -e OAUTH_HOSTNAME=http://localhost:8878 -e DEBUG=true --volume domi:/domiconfig.d -e ZOOM_CLIENT_ID=4wHhjxCQG6hPkyrPbjcQ -e ZOOM_CLIENT_SECRET=o8I3XNFJSSmCYB5XP2RNc8P5Qk7GtfmK -p 8878:8878 -p 8879:8879 docker.hcllabs.net/hclsoftware/domino-domi
2021-06-25 04:44:37 INFO  MainVerticle:393 - Metrics is configured for port 8879 with HTTPS
2021-06-25 04:44:37 INFO  MainVerticle:382 - *****************************
*** Running in debug mode ***
*****************************
2021-06-25 04:44:37 INFO  MainVerticle:382 - Starting up with hostname http://localhost:8878
2021-06-25 04:44:37 INFO  OnlineMeetingProviderFactoryHolder:393 - Enabled OAuth callback for Zoom at http://localhost:8878/zoomCallback
2021-06-25 04:44:37 WARN  OAuth2AuthHandlerImpl:? - route path changed to match callback URL
2021-06-25 04:44:37 INFO  OnlineMeetingProviderFactoryHolder:393 - Enabled OAuth validation for Zoom on paths http://localhost:8878/dominoZoom/*
2021-06-25 04:44:37 INFO  OnlineMeetingProviderFactoryHolder:393 - Enabled OAuth token revocation for Zoom at http://localhost:8878/dominoZoomRefresh
2021-06-25 04:44:37 INFO  OnlineMeetingProviderFactoryHolder:393 - Enabled OAuth token refresh for Zoom at http://localhost:8878/dominoZoomRefresh
2021-06-25 04:44:37 WARN  OnlineMeetingProviderFactoryHolder:386 - ***************
** Microsoft Teams client or secret not configured, endpoints will not be activated **
****************
2021-06-25 04:44:37 WARN  OnlineMeetingProviderFactoryHolder:386 - ***************
** Webex client or secret not configured, endpoints will not be activated **
****************
2021-06-25 04:44:37 WARN  OnlineMeetingProviderFactoryHolder:386 - ***************
** GoToMeeting client or secret not configured, endpoints will not be activated **
****************
2021-06-25 04:44:37 ERROR MainVerticle:382 -


 *********** FATAL **********



io.vertx.core.VertxException: OpenSSL is not available
        at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:76)
        at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:134)
        at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:168)
        at io.vertx.core.net.impl.TCPServerBase.<init>(TCPServerBase.java:76)
        at io.vertx.core.http.impl.HttpServerImpl.<init>(HttpServerImpl.java:61)
        at io.vertx.core.impl.VertxImpl.createHttpServer(VertxImpl.java:325)
        at com.hcl.labs.domi.MainVerticle.start(MainVerticle.java:298)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:40)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:121)
        at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:75)
        ... 17 more
```

**Additional context**
content of config.json

```
{
	"PORT": 8878,
	"METRICSPORT": 8879,
	
	"vertx": {
		
	},
	
	"TLSFile": "cert.pfx",
	"TLSPassword": "mySuperSecretPass0rd",
	"TLSType": "pfx",
	"cipher": {
		"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384": true,
		"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384": true,
		"TLS_RSA_WITH_AES_256_GCM_SHA384": true
	},
	"enabledProtocols": {
		"TLSv1.3": false,
		"TLSv1.2": true
	},
	"removeInsecureProtocols": {
		"TLSv1": true,
		"TLSv1.1": true,
		"SSLv2Hello": true
	},
	"CORS": {
		"localhost": true,
		"eknori.spdns.de": true,
		".local": true
	},
	"prometheusMetrics": {
		"embeddedServerEndpoint": "/metrics",
		"enabled": false,
		"publishQuantiles": true,
		"startEmbeddedServer": true
	}
}
```
Environment is CentOS with OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by eknori** [comment]
Could be this https://stackoverflow.com/questions/58184171/protocoll-adapter-start-fails-with-openssl-is-not-available

**Comment by eknori** [comment]
Created PR to add missing dependency

```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.34.Final</version>
      <scope></scope>
    </dependency>
```
